version: '3.9'

services:
  frontend:
    image: frontend/custom:1.1
    platform: linux/amd64
    restart: always
    container_name: 'explorer'
    env_file:
      - ../envs/common-explorer.env
