version: '3.9'

services:
  explorer:
    image: ghcr.io/blockscout/frontend:latest
    pull_policy: always
    platform: linux/amd64
    restart: always
    container_name: 'explorer'
    env_file:
      -  ../envs/common-explorer.env
