version: '3.9'

services:
  frontend:
    image: ghcr.io/blockscout/frontend:${FRONTEND_DOCKER_TAG:-latest}
    platform: linux/amd64
    restart: always
    container_name: 'explorer'
    env_file:
      - ../envs/common-explorer.env
